language: python
sudo: false

matrix:
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.4"
    env: TOXENV=py34
  - python: "pypy"
    env: TOXENV=pypy

install:
  - pip install -U setuptools pip wheel "tox>=3.4.0"
script:
  - env | sort

cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
