language: python
env:
  global:
    secure: BaDvppbzs10CcJTu0MTzsioFAl4fr1SY8iGkdCB6sfpaLQnQQ8eJvBwHbjeSLdanLPQwOv3MCkMKLT9NPC0dKhwiSo6ow+9GRAMK3td12zLntsJufAM7kCcS+fXzhxuaZSXolveLYKkASum+RZ0ldISnR2MUtxHUE15rZ1xSc9E=
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3

jobs:
  include:
    - name: 64-bit manylinux wheels (all Pythons)
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
      install: docker pull $DOCKER_IMAGE
      script: bash .manylinux.sh
    - name: 32-bit manylinux wheels (all Pythons)
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686 PRE_CMD=linux32
      install: docker pull $DOCKER_IMAGE
      script bash .manylinux.sh

before_install:

install:
- pip install -U setuptools pip wheel "tox>=3.4.0"

script:
- env | sort
- python --version
- python setup.py bdist_wheel
- tox
- cat .benchmark.csv.*

after_success:
- coverage combine
- coverage report
- coveralls
- echo [distutils]               > ~/.pypirc
- echo index-servers = pypi     >> ~/.pypirc
- echo [pypi]                   >> ~/.pypirc
- echo username=mete0r          >> ~/.pypirc
- echo password=$PYPIPASSWORD   >> ~/.pypirc
- if [[ $TRAVIS_TAG ]]; then pip install twine; fi
- if [[ $TRAVIS_TAG ]]; then python setup.py bdist_wheel; fi
- if [[ $TRAVIS_TAG ]]; then echo twine upload dist/*.whl; fi
- if [[ $TRAVIS_TAG ]]; then echo upload wheel disabled - requires manylinux platform tag; fi
cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
