language: python
sudo: false
matrix:
  include:
  - python: '2.7'
    env: TOXENV=py27
  - python: '3.4'
    env: TOXENV=py34
  - python: pypy
    env: TOXENV=pypy
install:
- pip install -U setuptools pip wheel "tox>=3.4.0" python-coveralls
script:
- env | sort
- python setup.py bdist_wheel
- tox
- cat .benchmark.csv.*
after_success:
- coverage combine
- coverage report
- coveralls
- echo [distutils]               > ~/.pypirc
- echo index-servers = pypi     >> ~/.pypirc
- echo [pypi]                   >> ~/.pypirc
- echo username=mete0r          >> ~/.pypirc
- echo password=$PYPIPASSWORD   >> ~/.pypirc
- if [[ $TRAVIS_TAG ]]; then pip install twine; fi
- if [[ $TRAVIS_TAG ]]; then python setup.py bdist_wheel; fi
- if [[ $TRAVIS_TAG ]]; then twine upload dist/*.whl; fi
deploy:
  provider: pypi
  twine_version: 1.13.0
  user: mete0r
  password:
    secure: EeecjW4fW5Nq+Mo/IINrqDiTvCpRBKBkznjwIA7XUQ59ox1vE0kEdun05JOgwIdt9w9lWt8Thum/BmIfG2J/35SIj7Xrv7ans0UvbtOodaED5jb5v7peV6ug0EOV7wukFWVVvLXuIjMNXQV5NgKxqy2wy24NGLGB3F+dGHDUCr8=
  on:
    tags: true
cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
env:
  global:
    secure: BaDvppbzs10CcJTu0MTzsioFAl4fr1SY8iGkdCB6sfpaLQnQQ8eJvBwHbjeSLdanLPQwOv3MCkMKLT9NPC0dKhwiSo6ow+9GRAMK3td12zLntsJufAM7kCcS+fXzhxuaZSXolveLYKkASum+RZ0ldISnR2MUtxHUE15rZ1xSc9E=
