image:
  - Visual Studio 2015

branches:
  only:
    - data2c

clone_folder: c:\projects\hypua2jamo

max_jobs: 2

environment:

  matrix:
    - python: 2.7
      TOXENV: py27
      ccompiler: ccompiler-vc90.cmd
    - python: 3.4
      TOXENV: py34
      ccompiler: ccompiler-winsdk71.cmd

platform:
  - x86

install:
  - cmd: |
      set
      cd
      cd c:\projects\hypua2jamo
      c:\python27\scripts\virtualenv .
      call scripts\activate
      pip install -U setuptools pip wheel "tox>=3.4.0"

build_script:
  - cmd: |
      CALL "%ccompiler%"
      python setup.py bdist_wheel

test_script:
  - cmd: |
      CALL "%ccompiler%"
      tox

artifacts:
  - path: 'dist\*.whl'
    name: wheel
  - path: '.benchmark.csv.*'
    name: benchmark.csv


deploy: off
