image:
  - Visual Studio 2015

branches:
  only:
    - data2c

clone_folder: c:\projects\hypua2jamo

max_jobs: 2

environment:

  matrix:
    - python: 2.7
      testscript: tox-py27.cmd
    - python: 3.4
      testscript: tox-py34.cmd

platform:
  - x86

init:
  - cmd: |
      cd c:\projects\hypua2jamo
      c:\python27\scripts\virtualenv .
      call scripts\activate

install:
  - cmd: |
      pip install -U setuptools pip "tox>=3.4.0"

build: off

test_script:
  - cmd: CALL "%testscript%"

deploy: off
