image:
  - Visual Studio 2015

clone_folder: c:\projects\hypua2jamo

environment:

  matrix:
    - python: 2.7
      testscript: tox-py27.cmd
    - python: 3.4
      testscript: tox-py34.cmd

platform:
  - x86

build:
  - CALL "%testscript%"
test: off
deploy: off
